### ISSUE TITLE
Скорректировать формаирование строки использования если есть Аргументы с типом Массив

### ISSUE THREAD

**Issue by khorevaa** [oscript-library/cli#10]
Сейчас необходимо формировать строку Спек в ручную
```bsl

	Команда.Аргумент("VERSION", , "Устанавливаемая версия OneScript. Допустимо использовать трехномерные версии (1.0.17, 1.0.18), latest, stable, dev, night-build")
					.ТМассивСтрок()
					.ВОкружении("OVM_OSCRIPT_VERSION");
	Команда.Спек = "VERSION...";
```

**Comment by khorevaa** [comment]
Сделано

**Comment by nixel2007** [comment]
Расскажи плиз, что мне нужно поправить в ovm теперь? убрать спек?

**Comment by khorevaa** [comment]
@nixel2007 Да после выхода следующей версии можно убрать просто спек... И должно работать

**Comment by nixel2007** [comment]
@khorevaa я правильно понимаю, что вот такое пока настройками аргумента/опции не задекларировать?
```
	КомандаПриложения.Спек = "VERSION APP [-- ARGS...]";
```

**Comment by khorevaa** [comment]
Между аргументами нет. Только 
между опциями и аргументами

**Comment by khorevaa** [comment]
@nixel2007 А напомни кейс почему оно не работает в строке по умолчанию

**Comment by nixel2007** [comment]
вроде была какая-то беда с необязательностью аргументов. надо блэйм глядеть :)

**Comment by nixel2007** [comment]
а, вспомнил! без `--` падал твой парсер на параметрах, начинающихся с минусов
типа `ovm run dev oscript -version`

**Comment by khorevaa** [comment]
@nixel2007 сделал тест все работает! )) Ура
