### ISSUE TITLE
Хотелось бы получать описание изменений в новых релизах

### ISSUE THREAD

**Issue by artbear** [oscript-library/cli#27]
+ новые релизы выпускаются, но что добавлено, непонятно.

+ И в майлстоунах интересно/непонятно :)
![image](https://user-images.githubusercontent.com/2920817/36028011-86a41394-0dae-11e8-80c1-1710fbbfc434.png)

**Comment by khorevaa** [comment]
@artbear Все будет ))  Просто еще не успел сделать описание..
Текущего выпущего релиза.

**Comment by khorevaa** [comment]
@artbear Да версии идут одновременно )) Как нужна появляется в функционале.

**Comment by khorevaa** [comment]
@artbear 
https://github.com/khorevaa/cli/releases/tag/0.9.8

**Comment by khorevaa** [comment]
Данный вопрос будет автоматизирован с https://github.com/khorevaa/orca
@artbear @nixel2007
