### ISSUE TITLE
Ошибка при распознавании опций

### ISSUE THREAD

**Issue by Morkhe** [oscript-library/cli#60]
Параметры команды:

	Команда.Опция("e extensions", Ложь, "Выгрузка конфигураций расширений")
			.ТБулево();

	Команда.Аргумент("PATH", , "Каталог для выгрузки")
			.ТСтрока();

Строка запуска:
`command -e`

Результат выполнения:
```
-e : Нет
PATH : -e
```

В readme написано, что аргументы отделяются от опций оператором "--". В данном случае включение опции распознается как значение аргумента.

**Comment by nixel2007** [comment]
У вас PATH обязательный аргумент. Предполагаю, что если запустить хотя бы `command -e .` , то все будет в порядке.

**Comment by Morkhe** [comment]
Да, в таком случае все будет в порядке. Но пользователь, не указавший аргумент, не узнает, что что-то идет не так)

**Comment by khorevaa** [comment]
Тут вопрос поиска пути (формирования строки использования) в общем кратко парсер находит 2 пути:
1. [-e ] -> PATH
2. PATH

Тестовые примеры работы парсера [тесты](https://github.com/khorevaa/cli/blob/develop/tests/%D0%9F%D0%B0%D1%80%D1%81%D0%B5%D1%80_test.os#L22)

Соответственно если задан только 1 аргумент, а опция необязательная, то выбирается самый короткий (ну это кратко)

т.е. бага нет - это запланированное поведение

По поводу README, суть в том, что если надо принудительно отделить аргументы от опций (в случае когда значение аргумента начинается с `-`) тогда надо использовать `--`. Можно так же это использовать для принудительного отделения. 

пример
`cmd -e temp -- -test_catalog `

В общем я к чему, данное поведение и проверку за корректность переданных аргументов командной строки уже должно отслеживать приложение, а не либа!

**Comment by Morkhe** [comment]
Тогда возможно стоит поправить readme, а то эта часть вводит в заблуждение:

>  Допустим, нужное нам имя файла равно -f, тогда если выполнить нашу команду:
> `ХочуФайл -f`
>
> то будет выдана ошибка, т.к. -f распознано как опция, а не аргумент. Для того, чтобы решить данную проблему, необходимо объявить окончание опций через оператор --
> `ХочуФайл -- -f`

Сейчас при одном аргументе у команды (без опций) параметр по первому сценарию распознается как аргумент, ошибок не выдает.

**Comment by khorevaa** [comment]
Хотя может и есть баг.. по идеи должен была распознаться как опция вида булево и ругнуться, что не передан аргумент. 

Признаю баг.. Кто хочет поправить? )))

**Comment by Morkhe** [comment]
Могу на выходных посмотреть, но у меня с тестами туго дело идет)
