### ISSUE TITLE
Падение приложения с опциями

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/cli#9]
https://github.com/khorevaa/cli/blob/develop/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/cmd/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F.os#L210

{Модуль C:\Program Files (x86)\OneScript\lib\cli\src\core\Классы\cmd\КомандаПриложения.os / Ошибка в строке: 210 / Ошибка при вызове метода контекста (СтрШаблон): Ошибка синтаксиса шаблона в позиции 1}

Видимо имелась ввиду либо вставка табуляции, либо вообще лишний процент в начале строки.

**Comment by nixel2007** [comment]
Воспроизведение:

```bsl

#Использовать cli

///////////////////////////////////////////////////////////////////////////////

Процедура ВыполнитьПриложение()
	
	КонсольноеПриложение = Новый КонсольноеПриложение("трам-пам-пам, "213123123");
	КонсольноеПриложение.Версия("v version", "1.0.0");
	
	// КонсольноеПриложение.УстановитьОсновноеДействие(ЭтотОбъект);
	КонсольноеПриложение.Запустить(АргументыКоманднойСтроки);
	
КонецПроцедуры

Попытка
	ВыполнитьПриложение();
Исключение
	Сообщить(ОписаниеОшибки());
КонецПопытки;

```

**Comment by nixel2007** [comment]
Исправлено в 0.9.4

**Comment by khorevaa** [comment]
-:)
